### ISSUE TITLE
Swap out p5.js for jQuery (or similar)

### ISSUE THREAD

**Issue by pieterdeschepper** [CodingTrain/Live-Poll#55]
This project is actually not using hardly any p5 specific code anymore, and it might benefit more from a library like jQuery to do the dom manipulation rather than have p5 still in there.

Any thoughts?

**Comment by shiffman** [comment]
I agree that this could make sense! I might like to hold off for a bit though as the community is less familiar with jQuery. I also like to push the limits and see how `p5.dom` performs. I also might suggest native JS rather than JQuery as a first step? But also I'm really not opposed to any and all options!

**Comment by pieterdeschepper** [comment]
Fine to stick with `p5.dom`
